name: Windows CI (Qt 6.9.2 MinGW)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python (for aqtinstall)
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install Qt 6.9.2 + MinGW 13.1
      shell: bash
      run: |
        aqt install-qt windows desktop 6.9.2 win64_mingw -O C:/Qt
        aqt install-tool windows desktop tools_mingw1310 -O C:/Qt

    - name: Configure PATH and CMAKE_PREFIX_PATH
      shell: pwsh
      run: |
        $env:PATH = "C:\Program Files\CMake\bin;C:\Qt\Tools\mingw1310_64\bin;C:\Qt\6.9.2\mingw_64\bin;$env:PATH"
        $env:CMAKE_PREFIX_PATH = "C:\Qt\6.9.2\mingw_64\lib\cmake"
        echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "CMAKE_PREFIX_PATH=$env:CMAKE_PREFIX_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Configure
      shell: pwsh
      run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: pwsh
      run: cmake --build build -- -j

    - name: Deploy default configs
      shell: pwsh
      run: cmake --build build --target qt_deploy_copy_configs

    - name: Test
      shell: pwsh
      run: ctest --test-dir build --timeout 120 --output-on-failure -V